version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - '5432:5432'
    volumes:
      - ./db:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - '5050:5050'
    volumes:
      - pgadmin:/root/.pgadmin
    restart: always

volumes:
  pgadmin: